image: docker:latest
services:
  - docker:dind
  - selenium/standalone-chrome:latest

stages:
  - build
  - test

before_script:
  - export DISPLAY=:1
  - sleep 3

maven-build:
  image: maven:3.6.3-jdk-11
  stage: build
  tags:
    - m5.large
  script:
    #- echo "executing script on branch ${branchName}"
    - "mvn clean -Dtest=ScenarioValuationReport test -DreTry=2 -Dbrowser -Denv -DgridUrl=http://selenium__standalone-chrome:4444/wd/hub"
  artifacts:
    when: always
    ....paths:
      - /builds/Aj821990/GeoPhyChallenge/screenshots/
      - /builds/Aj821990/GeoPhyChallenge/reports/